### ISSUE TITLE
HTTPS dose not work

### ISSUE THREAD

**Issue by limelect** [MFernstrom/XKCD-is-awesome#1]
https://xkcd.com/info.0.json dose not work error 443

I wrote my own ver on Delphi
and i got a handshake problem with sslv3 to down load the picture.
other sslv  did not even communicate.
 P.S as for the chuck norris i did not have any problem
with Delphi too.

**Comment by MFernstrom** [comment]
Should be fixed in 0.3 release.

I switched from fphttpclient to TNSHTTPSendAndReceive
